---
-  name:  Install NGINX
    ansible.builtin.package:
      name:  nginx
       state:  present

-  name:  Ensure NGINX  is  running  and enabled
    ansible.builtin.service:
      name:  nginx
       state:  started
      enabled:  yes

- name:  Deploy  index.html
   ansible.builtin.template:
       src:  index.html.j2
      dest:  "{{  webserver_root  }}/index.html"
      owner:  www-data
       group:  www-data
      mode:  "0644"
   notify:  Reload  nginx
